### ISSUE TITLE
Problem with GraphCrawl

### ISSUE THREAD

**Issue by SherifWaly** [opencharles/charles#92]
``GraphCrawlITCase.crawlsAllPages()`` test fails sometimes with ``WebDriverException`` error

**Comment by amihaiemil** [comment]
@SherifWaly Do you want to spend more time here, do some debugging, find out when exactly that "NoSuchElement" occurs? :D I assigned it to me, but I won't have time for this and I would like to know what exactly the problem is

**Comment by SherifWaly** [comment]
@amihaiemil Ok, I will debug it to find when the problem occurs exactly :)

**Comment by amihaiemil** [comment]
@SherifWaly Thank you :D

**Comment by amihaiemil** [comment]
We're going to try an remove phantomjs from IT, in #96
