### ISSUE TITLE
Links on different pages don't appear

### ISSUE THREAD

**Issue by SherifWaly** [opencharles/charles#93]
Links on a different page of a given url doesn't appear in the set of links returned. 
e.g. :``http://www.amihaiemil.com/2016/05/07/what-is-hateoas.html`` isn't found when the WebPage url is ``http://www.amihaiemil.com/`` but found at ``http://www.amihaiemil.com/page2/``

**Comment by amihaiemil** [comment]
This is a simple bug in the test, if I remember well. The index page is opened, which should contain that hateoas link. But in the meantime, the link has moved on page2 since pagination was introduced

**Comment by SherifWaly** [comment]
Yes, the link tested should be changed to another link at the first page.
